# Copyright 2024 NXP
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_HW_DEVICE_PART_MCXN236VNL=y

# Board project basic segments
#CONFIG_MCUX_PRJSEG_module.board.console_lite=y
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_PRJSEG_module.board.suite=y
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
# end of Board project basic segments
