/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
/*
 * How to setup clock using clock driver functions:
 *
 * 1. Setup clock sources.
 *
 * 2. Set up wait states of the flash.
 *
 * 3. Set up all dividers.
 *
 * 4. Set up all selectors to provide selected clocks.
 *
 */

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Clocks v20.0
processor: MCXN236
package_id: MCXN236VKL
mcu_data: ksdk2_0
processor_version: 26.06.20
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

#include "fsl_clock.h"
#include "clock_config.h"
#include "fsl_spc.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

/*******************************************************************************
 * Variables
 ******************************************************************************/
/* System clock frequency. */
extern uint32_t SystemCoreClock;

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/
void BOARD_InitBootClocks(void)
{
    BOARD_BootClockRUN();
}

/*******************************************************************************
 ********************** Configuration BOARD_BootClockRUN ***********************
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!Configuration
name: BOARD_BootClockRUN
called_from_default_init: true
outputs:
- {id: CLK_144M_clock.outFreq, value: 144 MHz}
- {id: CLK_48M_clock.outFreq, value: 48 MHz}
- {id: CLK_IN_clock.outFreq, value: 24 MHz}
- {id: FLEXCOMM4_clock.outFreq, value: 12 MHz, locked: true, accuracy: '0.001'}
- {id: FREQME_reference_clock.outFreq, value: 144 MHz}
- {id: FREQME_target_clock.outFreq, value: 144 MHz}
- {id: FRO_12M_clock.outFreq, value: 12 MHz}
- {id: FRO_HF_DIV_clock.outFreq, value: 48 MHz}
- {id: FRO_HF_clock.outFreq, value: 48 MHz}
- {id: MAIN_clock.outFreq, value: 150 MHz, locked: true, accuracy: '0.001'}
- {id: PLL0_CLK_clock.outFreq, value: 150 MHz}
- {id: Slow_clock.outFreq, value: 37.5 MHz, locked: true, accuracy: '0.001'}
- {id: System_clock.outFreq, value: 150 MHz, locked: true, accuracy: '0.001'}
- {id: gdet_clock.outFreq, value: 48 MHz}
- {id: trng_clock.outFreq, value: 48 MHz}
settings:
- {id: PLL0_Mode, value: Normal}
- {id: RunPowerMode, value: OD}
- {id: SCGMode, value: PLL0}
- {id: FLEXCOMM4CLKDIV_HALT, value: Enable}
- {id: FROHFDIV_HALT, value: Enable}
- {id: SCG.PLL0M_MULT.scale, value: '25'}
- {id: SCG.PLL0_NDIV.scale, value: '2'}
- {id: SCG.SCSSEL.sel, value: SCG.PLL0_CLK}
- {id: SCG_SOSCCSR_ERFES_SEL, value: CryOsc}
- {id: SCG_SOSCCSR_SOSCEN_CFG, value: Enabled}
- {id: SYSCON.FCCLKSEL4.sel, value: SYSCON.FRO_HF_DIV_CLK}
- {id: SYSCON.FLEXCOMM4CLKDIV.scale, value: '4'}
sources:
- {id: SCG.SOSC.outFreq, value: 24 MHz, enabled: true}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Variables for BOARD_BootClockRUN configuration
 ******************************************************************************/
/*******************************************************************************
 * Code for BOARD_BootClockRUN configuration
 ******************************************************************************/
void BOARD_BootClockRUN_InitClockModule(clock_module_t module)
{
    const pll_setup_t pll0Setup = {
        .pllctrl = SCG_APLLCTRL_SOURCE(0U) | SCG_APLLCTRL_SELI(15U) | SCG_APLLCTRL_SELP(7U),
        .pllndiv = SCG_APLLNDIV_NDIV(2U),
        .pllpdiv = SCG_APLLPDIV_PDIV(1U),
        .pllmdiv = SCG_APLLMDIV_MDIV(25U),
        .pllRate = 150000000U
    };

    /*!< Set up the clock sources */
    switch(module) {
        case kClockModule_SOSC:
            CLOCK_SetupExtClocking(24000000U);
            CLOCK_SetSysOscMonitorMode(kSCG_SysOscMonitorDisable);            /* System OSC Clock Monitor is disabled */
            break;
        case kClockModule_FIRC:
            CLOCK_SetupFROHFClocking(48000000U);               /*!< Enable FRO HF(48MHz) output */
            CLOCK_SetClkDiv(kCLOCK_DivFrohfClk, 1U);           /*!< Set FROHFDIV divider to value 1 */
            break;
        case kClockModule_SIRC:
            SCG0->SIRCCSR |= SCG_SIRCCSR_SIRC_CLK_PERIPH_EN_MASK; 
            break;
        case kClockModule_PLL0:
            /*!< Set up PLL0 */
            CLOCK_SetPLL0Freq(&pll0Setup);                       /*!< Configure PLL0 to the desired values */
            CLOCK_SetPll0MonitorMode(kSCG_Pll0MonitorDisable);            /* Pll0 Monitor is disabled */
            break;
        case kClockModule_PLLClk:
            CLOCK_AttachClk(kNONE_to_PLLCLKDIV);                 /*!< Switch gr PLLCLKDIV to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivPllClk);           /*!< Halt PLLCLKDIV divider */
            CLOCK_HaltClkDiv(kCLOCK_DivPLL1Clk0);           /*!< Halt PLL1CLK0DIV divider */
            CLOCK_HaltClkDiv(kCLOCK_DivPLL1Clk1);           /*!< Halt PLL1CLK1DIV divider */
            break;
        case kClockModule_CLK16K:
            CLOCK_SetupClk16KClocking(0U);      /* Enable the FRO 16kHz without any selected domain outputs */
            break;
        case kClockModule_FREQME:
            /* Configure FREQME clock */
            SYSCON->CLOCK_CTRL |=
                 SYSCON_CLOCK_CTRL_FRO_HF_ENA_MASK | SYSCON_CLOCK_CTRL_FRO12MHZ_ENA_MASK |
                 SYSCON_CLOCK_CTRL_CLKIN_ENA_FM_USBH_LPT_MASK; /* Enable FRO 1M, 12M and HF to frequency measure module */
            CLOCK_EnableClock(kCLOCK_InputMux);
            INPUTMUX->FREQMEAS_REF = INPUTMUX_FREQMEAS_REF_INP(2);
            INPUTMUX->FREQMEAS_TAR = INPUTMUX_FREQMEAS_REF_INP(2);
            break;
        case kClockModule_MAIN_CLOCK:
            CLOCK_AttachClk(kPLL0_to_MAIN_CLK);
            break;
        case kClockModule_SystemClk:
            CLOCK_SetClkDiv(kCLOCK_DivAhbClk, 1U);           /*!< Set AHBCLKDIV divider to value 1 */
            break;
        case kClockModule_CLKOUT:
            CLOCK_AttachClk(kNONE_to_CLKOUT);                 /*!< Switch CLKOUT to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivClkOut);           /*!< Halt CLKOUTDIV divider */
            break;
        case kClockModule_TRACEClk:
            CLOCK_AttachClk(kNONE_to_TRACE);                 /*!< Switch TRACE to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivTraceClk);           /*!< Halt TRACECLKDIV divider */
            break;
        case kClockModule_SYSTICK0Clk:
            CLOCK_AttachClk(kNONE_to_SYSTICK0);                 /*!< Switch SYSTICK0 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivSystickClk0);           /*!< Halt SYSTICKCLKDIV0 divider */
            break;
        case kClockModule_ADC0Clk:
            CLOCK_AttachClk(kNONE_to_ADC0);                 /*!< Switch ADC0 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivAdc0Clk);           /*!< Halt ADC0CLKDIV divider */
            break;
        case kClockModule_ADC1Clk:
            CLOCK_AttachClk(kNONE_to_ADC1);                 /*!< Switch ADC1 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivAdc1Clk);           /*!< Halt ADC1CLKDIV divider */
            break;
        case kClockModule_CTIMER0Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER0);                 /*!< Switch CTIMER0 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivCtimer0Clk);           /*!< Halt CTIMER0CLKDIV divider */
            break;
        case kClockModule_CTIMER1Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER1);                 /*!< Switch CTIMER1 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivCtimer1Clk);           /*!< Halt CTIMER1CLKDIV divider */
            break;
        case kClockModule_CTIMER2Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER2);                 /*!< Switch CTIMER2 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivCtimer2Clk);           /*!< Halt CTIMER2CLKDIV divider */
            break;
        case kClockModule_CTIMER3Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER3);                 /*!< Switch CTIMER3 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivCtimer3Clk);           /*!< Halt CTIMER3CLKDIV divider */
            break;
        case kClockModule_CTIMER4Clk:
            CLOCK_AttachClk(kNONE_to_CTIMER4);                 /*!< Switch CTIMER4 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivCtimer4Clk);           /*!< Halt CTIMER4CLKDIV divider */
            break;
        case kClockModule_OSTIMERClk:
            CLOCK_AttachClk(kNONE_to_OSTIMER);                 /*!< Switch OSTIMER to NONE */
            break;
        case kClockModule_EWMClk:
            CLOCK_AttachClk(kXTAL32K2_to_EWM0);                 /*!< Switch EWM0 to XTAL32K2 */
            break;
        case kClockModule_WDT0Clk:
            CLOCK_HaltClkDiv(kCLOCK_DivWdt0Clk);           /*!< Halt WDT0CLKDIV divider */
            break;
        case kClockModule_WDT1Clk:
            CLOCK_AttachClk(kCLK_1M_to_WDT1);                 /*!< Switch WDT1 to CLK_1M */
            CLOCK_HaltClkDiv(kCLOCK_DivWdt1Clk);           /*!< Halt WDT1CLKDIV divider */
            break;
        case kClockModule_CMP0Clk:
            CLOCK_AttachClk(kNONE_to_CMP0RR);                 /*!< Switch CMP0RR to NONE */
            CLOCK_AttachClk(kNONE_to_CMP0F);                 /*!< Switch CMP0F to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivCmp0FClk);           /*!< Halt CMP0FCLKDIV divider */
            CLOCK_HaltClkDiv(kCLOCK_DivCmp0rrClk);           /*!< Halt CMP0RRCLKDIV divider */
            break;
        case kClockModule_CMP1Clk:
            CLOCK_AttachClk(kNONE_to_CMP1RR);                 /*!< Switch CMP1RR to NONE */
            CLOCK_AttachClk(kNONE_to_CMP1F);                 /*!< Switch CMP1F to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivCmp1FClk);           /*!< Halt CMP1FCLKDIV divider */
            CLOCK_HaltClkDiv(kCLOCK_DivCmp1rrClk);           /*!< Halt CMP1RRCLKDIV divider */
            break;
        case kClockModule_FLEXCOMM0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCOMM0);                 /*!< Switch FLEXCOMM0 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexcom0Clk);           /*!< Halt FLEXCOMM0CLKDIV divider */
            break;
        case kClockModule_FLEXCOMM1Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCOMM1);                 /*!< Switch FLEXCOMM1 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexcom1Clk);           /*!< Halt FLEXCOMM1CLKDIV divider */
            break;
        case kClockModule_FLEXCOMM2Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCOMM2);                 /*!< Switch FLEXCOMM2 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexcom2Clk);           /*!< Halt FLEXCOMM2CLKDIV divider */
            break;
        case kClockModule_FLEXCOMM3Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCOMM3);                 /*!< Switch FLEXCOMM3 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexcom3Clk);           /*!< Halt FLEXCOMM3CLKDIV divider */
            break;
        case kClockModule_FLEXCOMM4Clk:
            CLOCK_AttachClk(kFRO_HF_DIV_to_FLEXCOMM4);                 /*!< Switch FLEXCOMM4 to FRO_HF_DIV */
            CLOCK_SetClkDiv(kCLOCK_DivFlexcom4Clk, 4U);           /*!< Set FLEXCOMM4CLKDIV divider to value 4 */
            break;
        case kClockModule_FLEXCOMM5Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCOMM5);                 /*!< Switch FLEXCOMM5 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexcom5Clk);           /*!< Halt FLEXCOMM5CLKDIV divider */
            break;
        case kClockModule_FLEXCOMM6Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCOMM6);                 /*!< Switch FLEXCOMM6 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexcom6Clk);           /*!< Halt FLEXCOMM6CLKDIV divider */
            break;
        case kClockModule_FLEXCOMM7Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCOMM7);                 /*!< Switch FLEXCOMM7 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexcom7Clk);           /*!< Halt FLEXCOMM7CLKDIV divider */
            break;
        case kClockModule_FLEXCAN0Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCAN0);                 /*!< Switch FLEXCAN0 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexcan0Clk);           /*!< Halt FLEXCAN0CLKDIV divider */
            break;
        case kClockModule_FLEXCAN1Clk:
            CLOCK_AttachClk(kNONE_to_FLEXCAN1);                 /*!< Switch FLEXCAN1 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexcan1Clk);           /*!< Halt FLEXCAN1CLKDIV divider */
            break;
        case kClockModule_FLEXIOClk:
            CLOCK_AttachClk(kNONE_to_FLEXIO);                 /*!< Switch FLEXIO to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivFlexioClk);           /*!< Halt FLEXIOCLKDIV divider */
            break;
        case kClockModule_I3C0Clk:
            CLOCK_AttachClk(kNONE_to_I3C0FCLK);                 /*!< Switch I3C0FCLK to NONE */
            CLOCK_AttachClk(kNONE_to_I3C0FCLKSTC);                 /*!< Switch I3C0FCLKSTC to NONE */
            CLOCK_AttachClk(kNONE_to_I3C0FCLKSlow);                 /*!< Switch I3C0FCLKSlow to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivI3c0FClk);           /*!< Halt I3C0FCLKDIV divider */
            break;
        case kClockModule_I3C1Clk:
            CLOCK_AttachClk(kNONE_to_I3C1FCLK);                 /*!< Switch I3C1FCLK to NONE */
            CLOCK_AttachClk(kNONE_to_I3C1FCLKSTC);                 /*!< Switch I3C1FCLKSTC to NONE */
            CLOCK_AttachClk(kNONE_to_I3C1FCLKSlow);                 /*!< Switch I3C1FCLKSlow to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivI3c1FClk);           /*!< Halt I3C1FCLKDIV divider */
            break;
        case kClockModule_SAI0Clk:
            CLOCK_AttachClk(kNONE_to_SAI0);                 /*!< Switch SAI0 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivSai0Clk);           /*!< Halt SAI0CLKDIV divider */
            break;
        case kClockModule_SAI1Clk:
            CLOCK_AttachClk(kNONE_to_SAI1);                 /*!< Switch SAI1 to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivSai1Clk);           /*!< Halt SAI1CLKDIV divider */
            break;
        case kClockModule_MICFILFClk:
            CLOCK_AttachClk(kNONE_to_MICFILF);                 /*!< Switch MICFILF to NONE */
            CLOCK_HaltClkDiv(kCLOCK_DivMicfilFClk);           /*!< Halt MICFILFCLKDIV divider */
            break;
        case kClockModule_UTICKClk:
            CLOCK_AttachClk(kCLK_1M_to_UTICK);                 /*!< Switch UTICK to CLK_1M */
            CLOCK_HaltClkDiv(kCLOCK_DivUtickClk);           /*!< Halt UTICKCLKDIV divider */
            break;
        default:
            assert(false);
            break;
    }
}

void BOARD_BootClockRUN(void)
{
    CLOCK_EnableClock(kCLOCK_Scg);                     /*!< Enable SCG clock */

    /* FRO OSC setup - begin, attach FRO12M to MainClock for safety switching */
    CLOCK_AttachClk(kFRO12M_to_MAIN_CLK);              /*!< Switch to FRO 12M first to ensure we can change the clock setting */

    /* Set the DCDC VDD regulator to 1.2 V voltage level */
    spc_active_mode_dcdc_option_t dcdcOpt = {
      .DCDCVoltage       = kSPC_DCDC_OverdriveVoltage,
      .DCDCDriveStrength = kSPC_DCDC_NormalDriveStrength,
    };
    SPC_SetActiveModeDCDCRegulatorConfig(SPC0, &dcdcOpt);
    /* Set the LDO_CORE VDD regulator to 1.2 V voltage level */
    spc_active_mode_core_ldo_option_t ldoOpt = {
      .CoreLDOVoltage       = kSPC_CoreLDO_OverDriveVoltage,
      .CoreLDODriveStrength = kSPC_CoreLDO_NormalDriveStrength,
    };
    SPC_SetActiveModeCoreLDORegulatorConfig(SPC0, &ldoOpt);
    /* Configure Flash wait-states to support 1.2V voltage level and 150000000Hz frequency */;
    FMU0->FCTRL = (FMU0->FCTRL & ~((uint32_t)FMU_FCTRL_RWSC_MASK)) | (FMU_FCTRL_RWSC(0x3U));
    /* Specifies the 1.2V operating voltage for the SRAM's read/write timing margin */
    spc_sram_voltage_config_t sramCfg = {
      .operateVoltage       = kSPC_sramOperateAt1P2V,
      .requestVoltageUpdate = true,
    };
    SPC_SetSRAMOperateVoltage(SPC0, &sramCfg);

    BOARD_BootClockRUN_InitClockModule(kClockModule_SOSC);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FIRC);
    BOARD_BootClockRUN_InitClockModule(kClockModule_SIRC);
    BOARD_BootClockRUN_InitClockModule(kClockModule_PLL0);
    BOARD_BootClockRUN_InitClockModule(kClockModule_CLK16K);
    BOARD_BootClockRUN_InitClockModule(kClockModule_MAIN_CLOCK);
    BOARD_BootClockRUN_InitClockModule(kClockModule_SystemClk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_PLLClk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_CLKOUT);
    BOARD_BootClockRUN_InitClockModule(kClockModule_TRACEClk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_SYSTICK0Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_ADC0Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_ADC1Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_CTIMER0Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_CTIMER1Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_CTIMER2Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_CTIMER3Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_CTIMER4Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_OSTIMERClk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_EWMClk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_WDT0Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_WDT1Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_CMP0Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_CMP1Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCOMM0Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCOMM1Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCOMM2Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCOMM3Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCOMM4Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCOMM5Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCOMM6Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCOMM7Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCAN0Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXCAN1Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FLEXIOClk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_I3C0Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_I3C1Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_SAI0Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_SAI1Clk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_MICFILFClk);
    BOARD_BootClockRUN_InitClockModule(kClockModule_FREQME);
    BOARD_BootClockRUN_InitClockModule(kClockModule_UTICKClk);

    /* Set SystemCoreClock variable */
    SystemCoreClock = BOARD_BOOTCLOCKRUN_CORE_CLOCK;
}

