/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

typedef enum {
    kClockModule_USBPHY,
    kClockModule_SOSC,
    kClockModule_FIRC,
    kClockModule_SIRC,
    kClockModule_PLL0,
    kClockModule_PLL1,
    kClockModule_PLLClk,
    kClockModule_MAIN_CLOCK,
    kClockModule_XTAL32K,
    kClockModule_CLK16K,
    kClockModule_RTC,
    kClockModule_SystemClk,
    kClockModule_SLOWClk,
    kClockModule_CLKOUT,
    kClockModule_TRACEClk,
    kClockModule_SYSTICK0Clk,
    kClockModule_SYSTICK1Clk,
    kClockModule_FLEXSPIClk,
    kClockModule_ADC0Clk,
    kClockModule_ADC1Clk,
    kClockModule_DAC0Clk,
    kClockModule_DAC1Clk,
    kClockModule_DAC2Clk,
    kClockModule_CTIMER0Clk,
    kClockModule_CTIMER1Clk,
    kClockModule_CTIMER2Clk,
    kClockModule_CTIMER3Clk,
    kClockModule_CTIMER4Clk,
    kClockModule_SCTClk,
    kClockModule_OSTIMERClk,
    kClockModule_EWMClk,
    kClockModule_WDT0Clk,
    kClockModule_WDT1Clk,
    kClockModule_USBClk,
    kClockModule_EMVSIM0Clk,
    kClockModule_EMVSIM1Clk,
    kClockModule_CMP0Clk,
    kClockModule_CMP1Clk,
    kClockModule_CMP2Clk,
    kClockModule_FLEXCOMM0Clk,
    kClockModule_FLEXCOMM1Clk,
    kClockModule_FLEXCOMM2Clk,
    kClockModule_FLEXCOMM3Clk,
    kClockModule_FLEXCOMM4Clk,
    kClockModule_FLEXCOMM5Clk,
    kClockModule_FLEXCOMM6Clk,
    kClockModule_FLEXCOMM7Clk,
    kClockModule_FLEXCOMM8Clk,
    kClockModule_FLEXCOMM9Clk,
    kClockModule_FLEXCAN0Clk,
    kClockModule_FLEXCAN1Clk,
    kClockModule_FLEXIOClk,
    kClockModule_uSDHCClk,
    kClockModule_SINCFILTClk,
    kClockModule_I3C0Clk,
    kClockModule_I3C1Clk,
    kClockModule_SAI0Clk,
    kClockModule_SAI1Clk,
    kClockModule_ENETClk,
    kClockModule_MICFILFClk,
    kClockModule_TSIClk,
    kClockModule_FREQME,
    kClockModule_PLUClk,
    kClockModule_UTICKClk,
} clock_module_t;

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ                         24000000U  /*!< Board xtal0 frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ********************** Configuration BOARD_BootClockRUN ***********************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockRUN configuration
 ******************************************************************************/
#define BOARD_BOOTCLOCKRUN_CORE_CLOCK             150000000U  /*!< Core clock frequency: 150000000Hz */
#define BOARD_BOOTCLOCKRUN_ROSC_CLOCK                     0U  /*!< ROSC clock frequency: 0Hz */

/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKRUN_ADC0_CLOCK                 0UL            /* Clock consumers of ADC0_clock output : ADC0 */
#define BOARD_BOOTCLOCKRUN_ADC1_CLOCK                 0UL            /* Clock consumers of ADC1_clock output : ADC1 */
#define BOARD_BOOTCLOCKRUN_CLK16K0_TOVBAT_CLOCK       0UL            /* Clock consumers of CLK16K0_toVBAT_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_CLK16K1_TOVSYS_CLOCK       0UL            /* Clock consumers of CLK16K1_toVSYS_clock output : CMP0, CMP1, LPTMR0, LPTMR1 */
#define BOARD_BOOTCLOCKRUN_CLK16K2_TOWAKE_CLOCK       0UL            /* Clock consumers of CLK16K2_toWAKE_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_CLK16K3_TOMAIN_CLOCK       0UL            /* Clock consumers of CLK16K3_toMAIN_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_CLKOUT_CLOCK               0UL            /* Clock consumers of CLKOUT_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_CLK_144M_CLOCK             144000000UL    /* Clock consumers of CLK_144M_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_CLK_1M_CLOCK               0UL            /* Clock consumers of CLK_1M_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_CLK_48M_CLOCK              48000000UL     /* Clock consumers of CLK_48M_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_CLK_IN_CLOCK               24000000UL     /* Clock consumers of CLK_IN_clock output : LPTMR0, LPTMR1 */
#define BOARD_BOOTCLOCKRUN_CMP0FDIV_CLOCK             0UL            /* Clock consumers of CMP0FDIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKRUN_CMP0RRDIV_CLOCK            0UL            /* Clock consumers of CMP0RRDIV_clock output : CMP0 */
#define BOARD_BOOTCLOCKRUN_CMP1FDIV_CLOCK             0UL            /* Clock consumers of CMP1FDIV_clock output : CMP1 */
#define BOARD_BOOTCLOCKRUN_CMP1RRDIV_CLOCK            0UL            /* Clock consumers of CMP1RRDIV_clock output : CMP1 */
#define BOARD_BOOTCLOCKRUN_CTIMER0_CLOCK              0UL            /* Clock consumers of CTIMER0_clock output : CTIMER0 */
#define BOARD_BOOTCLOCKRUN_CTIMER1_CLOCK              0UL            /* Clock consumers of CTIMER1_clock output : CTIMER1 */
#define BOARD_BOOTCLOCKRUN_CTIMER2_CLOCK              0UL            /* Clock consumers of CTIMER2_clock output : CTIMER2 */
#define BOARD_BOOTCLOCKRUN_CTIMER3_CLOCK              0UL            /* Clock consumers of CTIMER3_clock output : CTIMER3 */
#define BOARD_BOOTCLOCKRUN_CTIMER4_CLOCK              0UL            /* Clock consumers of CTIMER4_clock output : CTIMER4 */
#define BOARD_BOOTCLOCKRUN_EWM_CLOCK                  0UL            /* Clock consumers of EWM_clock output : EWM0 */
#define BOARD_BOOTCLOCKRUN_FLEXCAN0_CLOCK             0UL            /* Clock consumers of FLEXCAN0_clock output : CAN0 */
#define BOARD_BOOTCLOCKRUN_FLEXCAN1_CLOCK             0UL            /* Clock consumers of FLEXCAN1_clock output : CAN1 */
#define BOARD_BOOTCLOCKRUN_FLEXCOMM0_CLOCK            0UL            /* Clock consumers of FLEXCOMM0_clock output : LPI2C0, LPSPI0, LPUART0, LP_FLEXCOMM0 */
#define BOARD_BOOTCLOCKRUN_FLEXCOMM1_CLOCK            0UL            /* Clock consumers of FLEXCOMM1_clock output : LPI2C1, LPSPI1, LPUART1, LP_FLEXCOMM1 */
#define BOARD_BOOTCLOCKRUN_FLEXCOMM2_CLOCK            0UL            /* Clock consumers of FLEXCOMM2_clock output : LPI2C2, LPSPI2, LPUART2, LP_FLEXCOMM2 */
#define BOARD_BOOTCLOCKRUN_FLEXCOMM3_CLOCK            0UL            /* Clock consumers of FLEXCOMM3_clock output : LPI2C3, LPSPI3, LPUART3, LP_FLEXCOMM3 */
#define BOARD_BOOTCLOCKRUN_FLEXCOMM4_CLOCK            12000000UL     /* Clock consumers of FLEXCOMM4_clock output : LPI2C4, LPSPI4, LPUART4, LP_FLEXCOMM4 */
#define BOARD_BOOTCLOCKRUN_FLEXCOMM5_CLOCK            0UL            /* Clock consumers of FLEXCOMM5_clock output : LPI2C5, LPSPI5, LPUART5, LP_FLEXCOMM5 */
#define BOARD_BOOTCLOCKRUN_FLEXCOMM6_CLOCK            0UL            /* Clock consumers of FLEXCOMM6_clock output : LPI2C6, LPSPI6, LPUART6, LP_FLEXCOMM6 */
#define BOARD_BOOTCLOCKRUN_FLEXCOMM7_CLOCK            0UL            /* Clock consumers of FLEXCOMM7_clock output : LPI2C7, LPSPI7, LPUART7, LP_FLEXCOMM7 */
#define BOARD_BOOTCLOCKRUN_FLEXIO_CLOCK               0UL            /* Clock consumers of FLEXIO_clock output : FLEXIO0 */
#define BOARD_BOOTCLOCKRUN_FREQME_REFERENCE_CLOCK     144000000UL    /* Clock consumers of FREQME_reference_clock output : FREQME0 */
#define BOARD_BOOTCLOCKRUN_FREQME_TARGET_CLOCK        144000000UL    /* Clock consumers of FREQME_target_clock output : FREQME0 */
#define BOARD_BOOTCLOCKRUN_FRO_12M_CLOCK              12000000UL     /* Clock consumers of FRO_12M_clock output : LPTMR0, LPTMR1 */
#define BOARD_BOOTCLOCKRUN_FRO_HF_DIV_CLOCK           48000000UL     /* Clock consumers of FRO_HF_DIV_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_FRO_HF_CLOCK               48000000UL     /* Clock consumers of FRO_HF_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_I3C0_FCLK_CLOCK            0UL            /* Clock consumers of I3C0_FCLK_clock output : I3C0 */
#define BOARD_BOOTCLOCKRUN_I3C0_SLOW_TC_CLOCK         0UL            /* Clock consumers of I3C0_SLOW_TC_clock output : I3C0 */
#define BOARD_BOOTCLOCKRUN_I3C0_SLOW_CLOCK            0UL            /* Clock consumers of I3C0_SLOW_clock output : I3C0 */
#define BOARD_BOOTCLOCKRUN_I3C1_FCLK_CLOCK            0UL            /* Clock consumers of I3C1_FCLK_clock output : I3C1 */
#define BOARD_BOOTCLOCKRUN_I3C1_SLOW_TC_CLOCK         0UL            /* Clock consumers of I3C1_SLOW_TC_clock output : I3C1 */
#define BOARD_BOOTCLOCKRUN_I3C1_SLOW_CLOCK            0UL            /* Clock consumers of I3C1_SLOW_clock output : I3C1 */
#define BOARD_BOOTCLOCKRUN_LP_OSC_CLOCK               0UL            /* Clock consumers of LP_OSC_clock output : RTC0, TDET0, WUU0 */
#define BOARD_BOOTCLOCKRUN_MAIN_CLOCK                 150000000UL    /* Clock consumers of MAIN_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_MICFILFCLK_CLOCK           0UL            /* Clock consumers of MICFILFCLK_clock output : PDM */
#define BOARD_BOOTCLOCKRUN_OSTIMER_CLOCK              0UL            /* Clock consumers of OSTIMER_clock output : OSTIMER0 */
#define BOARD_BOOTCLOCKRUN_PLL0_CLK_CLOCK             150000000UL    /* Clock consumers of PLL0_CLK_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_PLL1_CLK_CLOCK             0UL            /* Clock consumers of PLL1_CLK_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_PLL_DIV_CLOCK              0UL            /* Clock consumers of PLL_DIV_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_SAI0_CLOCK                 0UL            /* Clock consumers of SAI0_clock output : SAI0 */
#define BOARD_BOOTCLOCKRUN_SAI1_CLOCK                 0UL            /* Clock consumers of SAI1_clock output : SAI1 */
#define BOARD_BOOTCLOCKRUN_FIRC_TRIM_CLOCK            0UL            /* Clock consumers of SCG.FIRC_TRIM_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_SIRC_TRIM_CLOCK            0UL            /* Clock consumers of SCG.SIRC_TRIM_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_SYSTICK0_CLOCK             0UL            /* Clock consumers of SYSTICK0_clock output : SysTick0 */
#define BOARD_BOOTCLOCKRUN_SLOW_CLOCK                 37500000UL     /* Clock consumers of Slow_clock output : CMC0, CMP0, CMP1, GPIO5, LPTMR0, LPTMR1, PORT5, RTC0, SPC0, TDET0 */
#define BOARD_BOOTCLOCKRUN_SYSTEM_CLOCK               150000000UL    /* Clock consumers of System_clock output : ADC0, ADC1, CAN0, CAN1, CMX_PERFMON0, CTIMER0, CTIMER1, CTIMER2, CTIMER3, CTIMER4, DMA0, DMA1, EVTG0, EWM0, FLEXIO0, FREQME0, GDET0, GDET1, GPIO0, GPIO0_ALIAS1, GPIO1, GPIO1_ALIAS1, GPIO2, GPIO2_ALIAS1, GPIO3, GPIO3_ALIAS1, GPIO4, GPIO4_ALIAS1, GPIO5_ALIAS1, I3C0, I3C1, INTM0, LPI2C0, LPI2C1, LPI2C2, LPI2C3, LPI2C4, LPI2C5, LPI2C6, LPI2C7, LPSPI0, LPSPI1, LPSPI2, LPSPI3, LPSPI4, LPSPI5, LPSPI6, LPSPI7, LPUART0, LPUART1, LPUART2, LPUART3, LPUART4, LPUART5, LPUART6, LPUART7, LP_FLEXCOMM0, LP_FLEXCOMM1, LP_FLEXCOMM2, LP_FLEXCOMM3, LP_FLEXCOMM4, LP_FLEXCOMM5, LP_FLEXCOMM6, LP_FLEXCOMM7, MRT0, OSTIMER0, PDM, PORT0, PORT1, PORT2, PORT3, PORT4, PUF, PUF_ALIAS1, PUF_ALIAS2, PUF_ALIAS3, PWM0, PWM1, QDC0, QDC1, SAI0, SAI1, SWD, SysTick0, USBHS1_PHY_DCD, UTICK0, WUU0, WWDT0, WWDT1 */
#define BOARD_BOOTCLOCKRUN_TRACE_CLOCK                0UL            /* Clock consumers of TRACE_clock output : SWD */
#define BOARD_BOOTCLOCKRUN_USB_HSPLL_CLOCK            0UL            /* Clock consumers of USB_HSPLL_clock output : USBHS1_PHY_DCD */
#define BOARD_BOOTCLOCKRUN_USB_PLL_CLOCK              0UL            /* Clock consumers of USB_PLL_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_UTICK_CLOCK                0UL            /* Clock consumers of UTICK_clock output : UTICK0 */
#define BOARD_BOOTCLOCKRUN_WDT0_CLOCK                 0UL            /* Clock consumers of WDT0_clock output : WWDT0 */
#define BOARD_BOOTCLOCKRUN_WDT1_CLOCK                 0UL            /* Clock consumers of WDT1_clock output : WWDT1 */
#define BOARD_BOOTCLOCKRUN_XTAL32K0_TOVBAT_CLOCK      0UL            /* Clock consumers of XTAL32K0_toVBAT_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_XTAL32K1_TOVSYS_CLOCK      0UL            /* Clock consumers of XTAL32K1_toVSYS_clock output : CMP0, CMP1, LPTMR0, LPTMR1 */
#define BOARD_BOOTCLOCKRUN_XTAL32K2_TOWAKE_CLOCK      0UL            /* Clock consumers of XTAL32K2_toWAKE_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_XTAL32K3_TOMAIN_CLOCK      0UL            /* Clock consumers of XTAL32K3_toMAIN_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_GDET_CLOCK                 48000000UL     /* Clock consumers of gdet_clock output : GDET0, GDET1 */
#define BOARD_BOOTCLOCKRUN_PLL1_CLK0_CLOCK            0UL            /* Clock consumers of pll1_clk0_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_PLL1_CLK1_CLOCK            0UL            /* Clock consumers of pll1_clk1_clock output : N/A */
#define BOARD_BOOTCLOCKRUN_TRNG_CLOCK                 48000000UL     /* Clock consumers of trng_clock output : N/A */


/*******************************************************************************
 * API for BOARD_BootClockRUN configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockRUN(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

