/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXN236
package_id: MCXN236VKL
mcu_data: ksdk2_0
processor_version: 26.06.20
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 96137720-7ec1-4b46-8e61-306cbe1ec401
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * LP_FLEXCOMM4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM4'
- type: 'lpflexcomm_lpuart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpuart_2.3.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM4'
- config_sets:
  - fsl_lpuart:
    - lpuartConfig:
      - timingConfig:
        - clockSource: 'LPFLEXCOMMFunctionClock'
        - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
        - baudRateBpsStr: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - rtsDelayValue: '1'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableSingleWire: 'false'
      - enableTx: 'true'
      - enableRx: 'true'
      - timeoutConfig:
        - rxExtendedTimeoutValue: '0'
        - txExtendedTimeoutValue: '0'
        - rxCounter0:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - rxCounter1:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - txCounter0:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - txCounter1:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LP_FLEXCOMM4_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableSingleWire = false,
  .rtsDelay = 0,
  .enableTx = true,
  .enableRx = true,
  .timeoutConfig = {
    .rxExtendedTimeoutValue = 0U,
    .txExtendedTimeoutValue = 0U,
    .rxCounter0 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .rxCounter1 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .txCounter0 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .txCounter1 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    }
  }
};

static void LP_FLEXCOMM4_init(void) {
  LPUART_Init(LP_FLEXCOMM4_PERIPHERAL, &LP_FLEXCOMM4_config, LP_FLEXCOMM4_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  LP_FLEXCOMM4_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
