/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE_dse1 0x01u /*!<@brief Drive Strength Enable: High */
#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */
#define PCR_SRE_sre1 0x01u /*!<@brief Slew Rate Enable: Slow */

/*! @name PORT3_6 (number 72), LED1_PIN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED1_PIN_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED1_PIN_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED1_PIN_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED1_PIN_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED1_PIN_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED1_PIN_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED1_PIN_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_1 (number 74), LED2_PIN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED2_PIN_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED2_PIN_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED2_PIN_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED2_PIN_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED2_PIN_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED2_PIN_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED2_PIN_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_8 (number 1), RXD_PIN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RXD_PIN_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RXD_PIN_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RXD_PIN_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_9 (number 2), TXD_PIN
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TXD_PIN_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TXD_PIN_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TXD_PIN_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
